#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "cockpit"
name = "Cockpit"
description.en = "Sysadmin login session in a Web browser"
description.fr = "Session de connexion sysadmin dans un navigateur Web"

version = "337~ynh2"

maintainers = []

[upstream]
license = "LGPL-2.1-only"
website = "https://cockpit-project.org/"
admindoc = "https://cockpit-project.org/documentation.html"
code = "https://github.com/cockpit-project/cockpit"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "150M"
ram.build = "50M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    help.en = "/cockpit/ and /cockpit+ are reserved and should not be used."
    help.fr = "/cockpit/ et /cockpit+ sont réservés et ne doivent pas être utilisés."
    type = "path"
    default = "/monitor"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 9090

    [resources.apt]
    packages = ["cockpit", "cockpit-bridge"]
